name: Export OPF

on: 
  issues:
    types: [opened]
    
jobs:
  export_opf:
    if: (github.event.issue.labels[0].name == 'export')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 1
    
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Install calibre
        run: |
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
          ebook-convert --version
      
      - name: install openpecha
        run: pip3 install openpecha
    
      - name: Export the opf
        run: |
          import os
          issue_body = os.getenv('ISSUE_BODY')
          layers, format = issue_body.splitlines()
          pwd = os.getcwd()
          repo_name = pwd.split('/')[-1]
          opf_path = f'{repo_name}/{repo_name}.opf'
          os.system(f'openpecha export -op {opf_path}')
        shell: python
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
      - name: Upload export to the latest release
        run: |
          from pathlib import Path
          from openpecha.github_utils import add_assets_to_latest_release
          
          pecha_num = Path.cwd().name
          exports_path = Path("./exports")
          add_assets_to_latest_release(pecha_num, exports_path.iterdir() if exports_path.is_dir() else [])
        shell: python
