# name: Test

# on: 
#   push

# jobs:
#   format:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: master
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v2
      
#       - name: Install calibre
#         run: |
#           sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
#           ebook-convert --version
