name: Update OPF

on: 
  issues:
    types: [opened]

jobs:
  # format HFML files and upload the opf artifact
  format:
    if: (github.event.issue.labels[0].name == 'update')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: publication
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v2
      - name: Format HFML
        run: |
          loc=$(pwd)
          repo_name=${loc##*/}
          # TODO: to be replaced by real formatter
          msg='update from publication with created by onwer'
          mkdir -p $repo_name.opf/layers/v002/
          mkdir -p $repo_name.opf/base
          echo $msg >> $repo_name.opf/layers/v002/pagination.yml
          echo $msg >> $repo_name.opf/base/v002.txt
          echo $msg >> $repo_name.opf/index2.yml
          
          mkdir formatted && mv $repo_name.opf formatted/
      - uses: actions/upload-artifact@v2
        with:
          name: opf
          path: formatted/
        
  update:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/download-artifact@master
        with: 
          name: opf
          path: formatted
      - name: update base and layer
        run: |
          loc=$(pwd)
          repo_name=${loc##*/}
          mv $repo_name.opf/meta.yml ./
          rm -rf $repo_name.opf
          mv formatted/* ./
          mv meta.yml $repo_name.opf/
          rm -rf formatted
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update pecha" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
